In [1]:
import numpy as np

In [2]:
x = [1,2,3]

In [3]:
x

[1, 2, 3]

In [4]:
type(x)

list

In [5]:
type(np.array(x))

numpy.ndarray

In [6]:
ndarr = type(np.array(x))

In [7]:
ndarr

numpy.ndarray

In [8]:
ndarr[3]

TypeError: 'type' object is not subscriptable

In [9]:
rangevar = np.arange(0,11)

In [10]:
rangevar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,11,100)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ,
        1.11111111,  1.22222222,  1.33333333,  1.44444444,  1.55555556,
        1.66666667,  1.77777778,  1.88888889,  2.        ,  2.11111111,
        2.22222222,  2.33333333,  2.44444444,  2.55555556,  2.66666667,
        2.77777778,  2.88888889,  3.        ,  3.11111111,  3.22222222,
        3.33333333,  3.44444444,  3.55555556,  3.66666667,  3.77777778,
        3.88888889,  4.        ,  4.11111111,  4.22222222,  4.33333333,
        4.44444444,  4.55555556,  4.66666667,  4.77777778,  4.88888889,
        5.        ,  5.11111111,  5.22222222,  5.33333333,  5.44444444,
        5.55555556,  5.66666667,  5.77777778,  5.88888889,  6.        ,
        6.11111111,  6.22222222,  6.33333333,  6.44444444,  6.55555556,
        6.66666667,  6.77777778,  6.88888889,  7.        ,  7.11111111,
        7.22222222,  7.33333333,  7.44444444,  7.55555556,  7.66

In [17]:
np.random.randint(0,10000,(5,5))

array([[ 702, 1710, 7024, 5161, 7213],
       [8058, 2087, 9884, 5181, 3990],
       [2099, 5098, 8861, 2737, 7304],
       [6013, 2637,  983, 9526, 7527],
       [7444, 2041, 3483, 6151, 5621]])

#this is a comment in jupyter notebook

In [19]:
np.random.seed(101)
np.random.randint(0,10000,(5,5))

array([[1547, 1361, 8006, 5695,  599],
       [6141, 4079,  973, 5672, 5764],
       [2623, 5032, 6460, 5824, 3182],
       [7173, 9100, 4573,   49, 9722],
       [4467, 1949, 2931, 2107, 5538]])

In [39]:
linArr = np.linspace(13,169,15)

In [40]:
linArr

array([ 13.        ,  24.14285714,  35.28571429,  46.42857143,
        57.57142857,  68.71428571,  79.85714286,  91.        ,
       102.14285714, 113.28571429, 124.42857143, 135.57142857,
       146.71428571, 157.85714286, 169.        ])

In [41]:
randArr = np.random.randint(2500,12500,(7,7))

In [42]:
randArr

array([[12272,  3773,  4823,  8258,  6307, 11035,  8749],
       [12219,  8883, 10242,  6248,  7575,  5671,  5856],
       [ 7427,  9163,  3406,  2936,  9394,  5901, 10104],
       [ 8022,  6075,  3851,  5459,  7108,  6958,  7760],
       [ 4751, 12179,  8485, 10657,  9320,  6275,  5046],
       [ 9186,  3800,  5471,  6348,  4378, 12215,  5498],
       [ 5289, 11713,  4209, 12118, 12286,  2739,  8736]])

In [62]:
randArr = np.random.randint(2500,12500,(6,6))

In [63]:
randArr

array([[10608,  4789,  6367,  8262,  8803,  3022],
       [ 4402,  6971,  4152,  2694,  8569,  8723],
       [ 6815, 11523,  3860,  9819,  9818,  6415],
       [11364,  9758,  8838,  9150, 11500,  9325],
       [12096, 10903, 12074,  7523,  8805, 10020],
       [ 2617,  2682,  5237,  3563,  9152,  5879]])

In [64]:
randArr.min()

2617

In [65]:
randArr.max()

12096

In [66]:
randArr.argmax()

24

In [67]:
randArr.argmin()

30

In [68]:
randArr.mean()

7669.388888888889

In [69]:
randArr.shape

(6, 6)

In [70]:
randArr

array([[10608,  4789,  6367,  8262,  8803,  3022],
       [ 4402,  6971,  4152,  2694,  8569,  8723],
       [ 6815, 11523,  3860,  9819,  9818,  6415],
       [11364,  9758,  8838,  9150, 11500,  9325],
       [12096, 10903, 12074,  7523,  8805, 10020],
       [ 2617,  2682,  5237,  3563,  9152,  5879]])

In [72]:
randArr.reshape(9,4)

array([[10608,  4789,  6367,  8262],
       [ 8803,  3022,  4402,  6971],
       [ 4152,  2694,  8569,  8723],
       [ 6815, 11523,  3860,  9819],
       [ 9818,  6415, 11364,  9758],
       [ 8838,  9150, 11500,  9325],
       [12096, 10903, 12074,  7523],
       [ 8805, 10020,  2617,  2682],
       [ 5237,  3563,  9152,  5879]])

In [73]:
randArr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [74]:
randArr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [75]:
randArr[35]

IndexError: index 35 is out of bounds for axis 0 with size 6

In [82]:
randArr[5][4]

9152

In [83]:
randArr[2][0]

6815

In [84]:
randArr = randArr.reshape(9,4)

In [85]:
randArr

array([[10608,  4789,  6367,  8262],
       [ 8803,  3022,  4402,  6971],
       [ 4152,  2694,  8569,  8723],
       [ 6815, 11523,  3860,  9819],
       [ 9818,  6415, 11364,  9758],
       [ 8838,  9150, 11500,  9325],
       [12096, 10903, 12074,  7523],
       [ 8805, 10020,  2617,  2682],
       [ 5237,  3563,  9152,  5879]])

In [86]:
randArr[2][3]

8723

In [87]:
randArr[3][2]

3860

In [88]:
randArr[:,3]

array([8262, 6971, 8723, 9819, 9758, 9325, 7523, 2682, 5879])

In [89]:
randArr[:,:]

array([[10608,  4789,  6367,  8262],
       [ 8803,  3022,  4402,  6971],
       [ 4152,  2694,  8569,  8723],
       [ 6815, 11523,  3860,  9819],
       [ 9818,  6415, 11364,  9758],
       [ 8838,  9150, 11500,  9325],
       [12096, 10903, 12074,  7523],
       [ 8805, 10020,  2617,  2682],
       [ 5237,  3563,  9152,  5879]])

In [90]:
randArr[3,:]

array([ 6815, 11523,  3860,  9819])

In [100]:
randArr[0:2,1:3]

array([[4789, 6367],
       [3022, 4402]])

In [101]:
randArr[0:2,:]

array([[10608,  4789,  6367,  8262],
       [ 8803,  3022,  4402,  6971]])

In [102]:
randArr[:,0:2]

array([[10608,  4789],
       [ 8803,  3022],
       [ 4152,  2694],
       [ 6815, 11523],
       [ 9818,  6415],
       [ 8838,  9150],
       [12096, 10903],
       [ 8805, 10020],
       [ 5237,  3563]])

In [103]:
randArr[randArr>10000]

array([10608, 11523, 11364, 11500, 12096, 10903, 12074, 10020])

In [104]:
myfilter = randArr>10000

In [105]:
randArr[myfilter]

array([10608, 11523, 11364, 11500, 12096, 10903, 12074, 10020])

In [106]:
myfilter

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [ True,  True,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])